version: '3.4'

x-defaults: &defaults
  restart: unless-stopped
  build: .
  depends_on:
    - redis
    - memcached
    - smtp

  environment:
    SENTRY_MEMCACHED_HOST: memcached
    SENTRY_REDIS_HOST: redis
    SENTRY_EMAIL_HOST: smtp
  volumes:
    - sentry-data:/var/lib/sentry/files


services:
  smtp:
    restart: unless-stopped
    image: tianon/exim4
    entrypoint: ["chamber", "exec", "sentry", "--"]

  memcached:
    restart: unless-stopped
    image: memcached:1.4
    entrypoint: ["chamber", "exec", "sentry", "--"]

  redis:
    restart: unless-stopped
    image: redis:3.2-alpine
    entrypoint: ["chamber", "exec", "sentry", "--"]

  web:
    <<: *defaults
    ports:
      - '9000:9000'
    entrypoint: ["chamber", "exec", "sentry", "--"]

  cron:
    <<: *defaults
    command: run cron
    entrypoint: ["chamber", "exec", "sentry", "--"]

  worker:
    <<: *defaults
    command: run worker
    entrypoint: ["chamber", "exec", "sentry", "--"]


volumes:
    sentry-data:
